version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:4000"   # now access backend at localhost:5000
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
    networks:
      - hrms-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27018:27017"   # now MongoDB accessible at localhost:27018
    volumes:
      - mongo-data:/data/db
    networks:
      - hrms-network

networks:
  hrms-network:

volumes:
  mongo-data:
